<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="23735" started-at="2018-03-31T13:34:31Z" finished-at="2018-03-31T13:34:54Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="23735" started-at="2018-03-31T13:34:31Z" finished-at="2018-03-31T13:34:54Z">
      <class name="com.hstm.assignment.flux1.testcases.AdminLoginPageTest">
        <test-method status="PASS" signature="initialSetUp()[pri:0, instance:com.hstm.assignment.flux1.testcases.AdminLoginPageTest@2173f6d9]" name="initialSetUp" is-config="true" duration-ms="11646" started-at="2018-03-31T13:34:31Z" finished-at="2018-03-31T13:34:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialSetUp -->
        <test-method status="FAIL" signature="loginPageTitleTest()[pri:1, instance:com.hstm.assignment.flux1.testcases.AdminLoginPageTest@2173f6d9]" name="loginPageTitleTest" duration-ms="26" started-at="2018-03-31T13:34:42Z" finished-at="2018-03-31T13:34:42Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Welcome to HealthStream expected:<Welcome to HealthStream> but was:<Actual Title is not matching with expected Title>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Welcome to HealthStream expected:<Welcome to HealthStream> but was:<Actual Title is not matching with expected Title>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
at com.hstm.assignment.flux1.testcases.AdminLoginPageTest.loginPageTitleTest(AdminLoginPageTest.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginPageTitleTest -->
        <test-method status="PASS" signature="hstmLogoTest()[pri:2, instance:com.hstm.assignment.flux1.testcases.AdminLoginPageTest@2173f6d9]" name="hstmLogoTest" duration-ms="146" started-at="2018-03-31T13:34:42Z" finished-at="2018-03-31T13:34:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- hstmLogoTest -->
        <test-method status="FAIL" signature="loginTest()[pri:3, instance:com.hstm.assignment.flux1.testcases.AdminLoginPageTest@2173f6d9]" name="loginTest" duration-ms="10975" started-at="2018-03-31T13:34:42Z" finished-at="2018-03-31T13:34:53Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Site Map expected:<Site Map> but was:<Title is not Matching!>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Site Map expected:<Site Map> but was:<Title is not Matching!>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
at com.hstm.assignment.flux1.testcases.AdminLoginPageTest.loginTest(AdminLoginPageTest.java:56)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:com.hstm.assignment.flux1.testcases.AdminLoginPageTest@2173f6d9]" name="closeBrowser" is-config="true" duration-ms="899" started-at="2018-03-31T13:34:53Z" finished-at="2018-03-31T13:34:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- com.hstm.assignment.flux1.testcases.AdminLoginPageTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
